# Generated by Django 3.1.5 on 2021-01-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', null=True, upload_to='event/images')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('product', models.ManyToManyField(blank=True, related_name='product', to='products.Product')),
            ],
        ),
    ]
