# Generated by Django 3.1.5 on 2021-01-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210111_1312'),
        ('notifications', '0004_auto_20210113_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_from_user', to='profiles.profile'),
        ),
    ]
