# Generated by Django 3.1.5 on 2021-01-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, max_length=300)),
                ('image1', models.ImageField(default='', null=True, upload_to='products/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='products/images')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('product', models.ManyToManyField(related_name='products', to='products.Product', verbose_name='Product')),
            ],
        ),
    ]
