# Generated by Django 3.1.5 on 2021-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_category',
            field=models.CharField(choices=[('Footer', 'Footer'), ('Homepage', 'Homepage'), ('Event', 'Event')], default='', max_length=10),
        ),
    ]
