# Generated by Django 3.1.5 on 2021-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210114_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product', verbose_name='Product'),
        ),
    ]
