# Generated by Django 3.1.5 on 2021-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210114_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_category',
            field=models.CharField(choices=[('Footer', 'Footer'), ('Homepage', 'Homepage'), ('Event', 'Event')], max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='product',
            field=models.ManyToManyField(related_name='products', to='products.Product', verbose_name='Product'),
        ),
    ]
