# Generated by Django 3.1.5 on 2021-01-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210114_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='ad_category',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='img',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='advertise'),
        ),
    ]
